<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QHTT137" failures="1" tests="9" name="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" time="43.931" errors="0" timestamp="03 Nov 2021 16:57:05 GMT" skipped="0">
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase1" time="2.894"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase2" time="8.685"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase3" time="4.369"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase4" time="1.973"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase5" time="3.209">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test.linkedlist_Implement_testcase5(linkedlist_Implementpython_Test.java:156)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- linkedlist_Implement_testcase5 -->
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase6" time="8.351"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase7" time="8.296"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase8" time="1.711"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test" name="linkedlist_Implement_testcase9" time="4.443"/>
</testsuite> <!-- com.numpy_ninja.dsalgo.tests.linkedlist_Implementpython_Test -->
